### ISSUE TITLE
Can not build without <float.h>

### ISSUE THREAD

**Issue by michalspondr** [yellingintothefan/gel#3]
I had to add
`#include <float.h>`
otherwise I got this error message:

> main.c: In function ‘reset’:
> main.c:449:21: error: ‘FLT_MAX’ undeclared (first use in this function)
>          zbuff[i] = -FLT_MAX, pixel[i] = 0x0;

I am using gcc version 6.4.0.

**Comment by yellingintothefan** [comment]
Thanks, patching.
